# Generated by Django 4.2.7 on 2023-11-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='persona_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_administrador', to='usuario.persona', verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='compra',
            name='persona_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_proveedor', to='usuario.persona', verbose_name='Proveedor'),
        ),
    ]
